### ISSUE TITLE
Contribution: Tree prompt plugin

### ISSUE THREAD

**Issue by insightfuls** [SBoudrias/Inquirer.js#1009]
Dear maintainers, I've created a generic tree prompt:

https://www.npmjs.com/package/inquirer-tree-prompt

If you think it might be helpful to others, you could mention it in your README.

**Comment by LitoMore** [comment]
Hi @insightfuls! Thank you for creating this awesome plugin for Inquirer.js!

You could create a PR to add your plugin to our readme.

BTW, I have some suggestions for your plugin:

- Select a [license](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) for your project
- [Record an SVG video](https://github.com/marionebl/svg-term-cli) instead of GIF (vectors have a better visual)
- Add a `Related` section to mention [Inquirer.js](https://github.com/SBoudrias), you could refer to this [example](https://github.com/LItoMore/inquirer-chalk-pipe).
