### ISSUE TITLE
Edit or disable List prompt suffix text (Use arrow keys)

### ISSUE THREAD

**Issue by redpwilliams** [SBoudrias/Inquirer.js#1016]
## Example
![image](https://user-images.githubusercontent.com/57783597/119898666-210fd600-bf10-11eb-8661-dd45ba33cefc.png)

## Feature Request
It would be nice if I can edit that, much like the `prefix` and `suffix` arguments for the `Question` object, or remove it all together. Is this already possible?

**Comment by Red-CS** [comment]
I looked at more of the codebase, and I found where the change would go. I am not making a PR yet because I don't know if this is intended behavior based on how this is written:

In `Inquirer.js\packages\inquirer\lib\prompts\list.js`:
```js
if (this.firstRender) {
      message += chalk.dim('(Use arrow keys)');
}
```
I understand that `suffix` is already appended to `message` in the Super `base.js`: (for reference)
```js
getQuestion() {
    let message =
      this.opt.prefix +
      ' ' +
      chalk.bold(this.opt.message) +
      this.opt.suffix +
      chalk.reset(' ');
. . .
```
If this is intended behavior, an easy fix might be adding an option to enable, disable, or set that string ("Use arrow keys"). A larger fix might be leaving the `prefix`/`suffix` concatenation for the subclasses for more specific use, and just passing `message` as is.

What do you think?

**Comment by SBoudrias** [comment]
This is now configurable through `theme.helpMode`; `never` or `always` (default to `auto`)
