### ISSUE TITLE
TypeScript destroys code

### ISSUE THREAD

**Issue by xaronnn** [SBoudrias/Inquirer.js#1054]
After i compile TS, code will destroy.

inquirer_1["default"].registerPrompt("table", inquirer_table_prompt_1["default"]);
                      ^
TypeError: Cannot read property 'registerPrompt' of undefined

**Comment by SBoudrias** [comment]
`require('inquirer').default` is undefined. Looks like your build process is making wrong assumption about the package structure (often seen by Babel es-module compilation.)

Since this is not an issue with Inquirer, I'll close the issue. But feel free to follow-up once you figure out the issue on your side; this could be useful to other people running into similar problem.
