### ISSUE TITLE
Changelog location - breaking 7 -> 8 change? and npm version vs github tags

### ISSUE THREAD

**Issue by j-d-carmichael** [SBoudrias/Inquirer.js#1097]
Is there a changelog for this project?

I have a tool on version 7 and wondering what the breaking change to version 8 is.

Also, the last tag on github is 6 which misaligns with the npm version https://www.npmjs.com/package/inquirer

Thanks

**Comment by SBoudrias** [comment]
Hi, the changelog is maintained on the _Releases_ tab on github: https://github.com/SBoudrias/Inquirer.js/releases

Specifically, 8.0 is here: https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%408.0.0

Around the time version 6 went out, I started a refactor project to ship smaller footprint prompts. As part of this, the repo became a monorepo; so the tag naming convention changed. The releases post v6.x are tagged as `inquirer@x.x.x`. And you'll see tags for the beta prompts part of the refactor.

**Comment by SubJunk** [comment]
@SBoudrias At the time of writing, the latest changelog on the Releases tab is 9.1.4, but the latest tag is 9.2.6. How do we know what has changed?

**Comment by LitoMore** [comment]
@SubJunk All `inquirer` related changes are in the `packages/inquirer` directory. So you can check its commit history: https://github.com/SBoudrias/Inquirer.js/commits/master/packages/inquirer.

**Comment by SBoudrias** [comment]
@LitoMore yeah, the big problem I have is lerna generates a lot of versions who're not necessary (or that I would skip releasing since they're dev only changes.)

I'm considering moving versioning to changeset instead of Lerna; but not sure when that'll happen.

For now, significant releases have notes in the release tab; you can assume other versions are version bumps or dev only changes.
