### ISSUE TITLE
Password does not get cleared using backspace or delete in windows

### ISSUE THREAD

**Issue by sauravraw** [SBoudrias/Inquirer.js#1128]
I am making a package where users need to do login by using `oclif` package.

The login functionality works fine in **Linux OS** and **Mac OS** where the user can do both backspaces and delete if user enters the wrong password but in **Windows**, it's totally the opposite in place of removing the wrong input it keeps on adding `*` when user press backspace and delete button please look into this 

Node version:- 16.15.1
inquirer: "^8.2.3",
oclif: 3.0.1

**Comment by sauravraw** [comment]
Hi team, any update regarding this issue, Like when will be resolved? 

Thank you in advance :)

**Comment by akashroy1** [comment]
I want to work on this issue please guide me.

**Comment by SBoudrias** [comment]
@sauravraw I'm not able to reproduce. So I'll need more input/details/help from you to make any progress.

FWIW, inquirer is downloaded and used a LOT. If windows was broken for everyone, I think we'd have seen many more people bringing the issue up here - but it's not been the case. I would start debugging with the assumption the issue is somewhat specific to your environment, or inquirer is used inside your app code.

Also, did you try out with `import { password } from '@inquirer/prompts'`?

**Comment by LitoMore** [comment]
I tried `inquirer@8` on both Command Prompt and PowerShell, and can't reproduce this issue on my Windows 11.

**Comment by SBoudrias** [comment]
I'll close due to inactivity.
