### ISSUE TITLE
How to answer prompts programatically? 

### ISSUE THREAD

**Issue by mshaaban0** [SBoudrias/Inquirer.js#1152]
Hi, Is there a way to answer prompts from code when an events happens. example:

```js
emitter.on('token', params => {
  const token = params.get('token')
  if (!token) return
  stdin.write(`${token}\n`)  // doesn't work, outputs unmasked text, and inquirer isn't listening to it
})

const tokenAnswer = await inquirer.prompt([
  {
    type: 'password',
    name: 'token',
    message: 'Paste your token here:',
    mask: true
  }
])
```

**Comment by SBoudrias** [comment]
There's no simple way to pass text to inquirer like if a user was inputting it. You might be able to hack something if you find a way to access inquirer `readline` instance and write to it; but I cannot guarantee this'll keep working in the future.

Why not simply skip the prompt if you have the token?

Otherwise another option is to implement a custom prompt with your own logic doing this. See this core prompt for example https://github.com/SBoudrias/Inquirer.js/tree/master/packages/select

**Comment by mshaaban0** [comment]
Thanks, I managed to skip the prompt using `...ui.close()`

```js
const tokenAnswer = await inquirer.prompt([
  {
    type: 'password',
    name: 'token',
    message: 'Paste your token here:',
    mask: true
  }
]);

tokenAnswer.ui.close();

```
