### ISSUE TITLE
Cannot use import statement outside a module: using jest

### ISSUE THREAD

**Issue by alphmth** [SBoudrias/Inquirer.js#1168]
I am trying to upgrade `inquirer` in my project but it's not allowing me to upgrade as I am getting a `Cannot use import statement outside a module` error when doing the upgrade. My project is ESM as well. I have mimicked the project and attached here 
[ts-project.zip](https://github.com/SBoudrias/Inquirer.js/files/9665956/ts-project.zip)

```
 import { default as List } from './prompts/list.js';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

   
    > 2 | import inquirer from 'inquirer';

        | ^
      3 |
      4 | describe('inquirer module', () => {
      5 |   test('inquirer example', () => {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1678:14)
      at Object.<anonymous> (test/sum.test.ts:2:1)
```

**Comment by alphmth** [comment]
I am trying to upgrade this project https://github.com/jaredwray/writr/issues/131

**Comment by kenchoong** [comment]
same, did you configure this out? @alphmth

**Comment by SBoudrias** [comment]
Hi, I would recommend this guide going over multiple guides to make your node project ESM compatible. It's a bit painful, but once configured it should work properly: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

This error you're having is because it's mixing ESM and commonjs modules.

I'll close as not something directly related to inquirer; but feel free to keep discussing/debugging on this thread. Otherwise, you can also use the discussion section for this.
