### ISSUE TITLE
feat: Multiselect with ArrowKeys

### ISSUE THREAD

**Issue by Yevhenii-Bakhmat** [SBoudrias/Inquirer.js#1175]
Guys from t3-oss and nuxtjs are using the Inquirer and I personally ran at QoL issue.
When you are using the checkboxes, you can select them only with 'space' key
![image](https://user-images.githubusercontent.com/34962307/194720136-cf8394fd-4877-4401-86e0-812e571f7ca3.png)

```ts
  } else if (isSpaceKey(key)) {
        setShowHelpTip(false);
        setChoices(
          choices.map((choice, i) => {
            if (i === cursorPosition) {
              return { ...choice, checked: !choice.checked };
            }

            return choice;
          })
        );
```

SO basically id love to be able to check and uncheck those checkboxes with right and left arrow buttons. I feel like it will be easier coz you'll be able to use buttons that are really close together.

**Comment by SBoudrias** [comment]
Hi, thanks for sending the suggestion. I've choosen the current keyboard controls because they are the one your OS already use for such controls on their UI and on the web. Try pressing space and see it'll tick/untick UI checkboxes on your computer.

This just felt like a good "fairly" known default to mimic.

**Comment by Yevhenii-Bakhmat** [comment]
Fair enough
