### ISSUE TITLE
Checkboxes disable other choices based on selection

### ISSUE THREAD

**Issue by eddiemonge** [SBoudrias/Inquirer.js#118]
Itd be nice to have the choices in a checkbox be able to be disabled if one of the choices is checked.

choices:
- [ ] I am not disabled
- [ ] only I can be checked

---
- I am now disabled - disabled
- [x] only I can be checked

**Comment by sabsaxo** [comment]
Radio Buttons vs Checkboxes?

**Comment by macrolo** [comment]
<div style="    padding-left: 37px;margin-top: -45px;" class="col-md-12">
                                    <div class="form-group col-md-6 " style="padding-left: 0;">
                                        <label style="font-size: 18px;color: green;" class="control-label" for="title">Yes</label>
                                        <input type="checkbox" id="yes" name="docketTitle"  required="required" >
                                    </div>
                                    <div class="form-group col-md-6 " style="padding-left: 0;">
                                        <label style="    font-size: 18px;color: #ffc543;" class="control-label" for="title">No</label>
                                        <input type="checkbox" id="no" name="docketTitle"  required="required" >
                                    </div>
                                </div>
<script type="text/javascript">
        $("#yes").on("click", function () {
            var yesDocket = document.getElementById('no');
            yesDocket.checked = false;
        });
        $("#no").on("click", function () {
            var noDocket = document.getElementById('yes');
            noDocket.checked = false;
        });
    </script>

**Comment by macrolo** [comment]
$("#yes").on("click", function () {
            var yesDocket = document.getElementById('no');
            yesDocket.checked = false;
        });

        $("#no").on("click", function () {
            var noDocket = document.getElementById('yes');
            noDocket.checked = false;
        });

**Comment by GeorgeGkas** [comment]
It seems that this issue needs a more UX Design approach ("How to make the prompts more user friendly?") than a strictly programmatic answer. I agree with the options provided by @SBoudrias. If you have a prompt where you only need to select one answer, and disable all the others, then use [list](https://github.com/SBoudrias/Inquirer.js#list---type-list) or [rawlist](https://github.com/SBoudrias/Inquirer.js#raw-list---type-rawlist) type. By the time you have to choose more than one answers, you go for [checkboxes](https://github.com/SBoudrias/Inquirer.js#checkbox---type-checkbox). But what happens when you have to conditionally choose items from a list?

Let's try to find a solution for the [generator-angular](https://github.com/SBoudrias/Inquirer.js/issues/118#issuecomment-44308332) use case:

First we have to understand that it's a good design decision to create prompts that serve only one purpose. This is called Grouping, to divide a list of items based on a reason which makes sense in the context of the use case. 

In your example, we can extract the options "Angular Router" and "UI Router" into a separate prompt. Both items relates with routing, where all the other serve more abstract choices (do not relate with each other). By doing this we achieve the following results:

- Increase the usability (effectiveness, efficiency and satisfaction) of the design.
- Conforms to *Don’t Make Me Think* principle: People don’t like to puzzle over how to do things. The human mind needs more time to interpret texts that contain conditions (click this or do not click the other) which, especially in large scale, frustrate us. Consider a list with 50 choices and 20 conditionals. 
- Conforms to *Don’t waste my time* principle: More thinking = more time to interpret messages = more time to take action = more frustration *[citation needed]*.

This explanation does not relate only for this specific use case. You can argue that the list is small, but what will happen if implement this feature? Someone can be tempted and use this conditional-chose-list for everything. It's not an unrealistic example as we have seen in many aspects of our lives as programmers that users prefer the simple, easy, sometimes dreadful choice, to save them some time.

**By not implementing this feature, the user will necessarily go for two lists, which is the optimal UX**. You see, even if the user cannot extract the reasoning I have already described, he still will make the right decision by grouping items in distinct lists. 

@eddiemonge have you understand the explanation? Does anyone else wants to say anything? If we are done, then @SBoudrias you can close this issue.

**Comment by GalawynRM** [comment]
I found this solution, that works for me, maybe for someone else

`choices: (answers)=> { return [
                    {name:'DTOs', value: 'dto'},
                    {name:'DB', value: 'sql', disabled: answers.generateFrom == 'db'}
                ]`
