### ISSUE TITLE
Unable to use clipboard and paste in input type.

### ISSUE THREAD

**Issue by IcAkA969** [SBoudrias/Inquirer.js#1190]
Im unable to paste any text when using the input type

Do I need to use something different from the input type in order to be able to paste text ?

Im using the 8.0.0 version.

**Comment by SBoudrias** [comment]
Hi, thanks for reaching out! Seems like we can configure the stream to handle it with:

```js
const readline = require('readline');
readline.emitKeypressEvents(process.stdin);
process.stdin.setRawMode(true);
```

Since this has side-effects on the `stdin`, I'm not 100% sure Inquirer should be doing it internally. That being said, I am definitively open to it, especially if we can scope it. Would you be willing to work on a PR looking into this?

In the short term, calling those 2 lines above before calling inquirer should (theoretically) make pasting in the input prompt work as expected.

**Comment by IcAkA969** [comment]
I tried it, still doesn't work for some reason...

**Comment by SBoudrias** [comment]
Are you running the script with `node` or some other tools? (like `nodemon`)

**Comment by IcAkA969** [comment]
I am running it with node.
