### ISSUE TITLE
Combine multiple state updates into a single operation to reduce renders

### ISSUE THREAD

**Issue by JonathanCoxLRS** [SBoudrias/Inquirer.js#1251]
Example: I have 2 state properties as shown below.

```javascript
const [a, setA] = useState(config.a ? config.a : null);
const [b, setB] = useState(config.b ? config.b : null);
```

Calling either ``setA`` or ``setB`` initiates a render.

As part of my app logic, there are situations in which both ``a`` and ``b`` need to be updated.  However, rendering twice is undesirable as it results in visual flicker.  Does the core library provide a way to combine those updates such that only one render is required?

I suppose I can rewrite my code to have a single ``properties`` property like this:

```javascript
const [properties, setProperties] = useState(
	Object.freeze(
		{
			a: config.a ? config.a : null,
			b: config.b ? config.b : null
		}
	)
);
```

Then, I can update multiple properties like this:

```javascript
setProperties(
	Object.freeze(
		Object.assign(
			{
				a: 1,
				b: 2
			},
			properties
		)
	)
);
```

What's the best practice to accomplish this?  I'd rather use features of the core library than write my own workarounds for the state system.

Thanks!

**Comment by SBoudrias** [comment]
Hi! Thanks for bringing that feedback

I want to batch renders to handles cases like what you outlined. I didn't have time yet to implement, but it's definitively an update the would make sense.

The [code is over here](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/core/src/index.mts#L67-L68C16) if you want to give it a try. The tests should catch any regression you'd introduce (I think they're end-to-end enough to not bulk on delayed re-renders; but might need to review that too.)

**Comment by SBoudrias** [comment]
Implemented a naïve version of this.

So on any sync functions, the state updates will be merged (See code at https://github.com/SBoudrias/Inquirer.js/commit/165d6d80b9e2df7c82775c72fbfefea402406acf)

But it won't work if calling multiple times `setState` from within an async callback (like `setTimeout`.) Handling those would require to have asynchronous rendering loops, and that makes everything more complicated (testing, but also just things like making sure there's no delays when typing.) Since updating multiple states from async functions are not a pattern I've encountered often creating prompts, I'm leaning on the side of simplicity for now.

(And the code demo using an object state is a good work around for custom prompt requiring multi state updates from an async callback.)
