### ISSUE TITLE
Add validate function to checkbox 

### ISSUE THREAD

**Issue by tinchox5** [SBoudrias/Inquirer.js#1257]
Hi, It would be great to have a validate function on checkbox package. I know items should be valid since user only have to choose between them. But validate is still needed. For instance, what happend is user doesnt pick an option? what if one of two options must me select to continue? 
This behaviour was contemplated previuosly but is not available now in the Checkbox package.

**Comment by SBoudrias** [comment]
PR welcomed if anyone wants to take it up! (I might get to it eventually, but don't know when)

**Comment by mastrzyz** [comment]
I'll take a look into this :)

**Comment by Srenky** [comment]
Hi hi, I'd like to work on this issue since it still looks available. I have a uni assignment to make some contribution to OSS and this issue caught my eye. Adding validation for cases when no checkbox is selected seems reasonable. Also, adding an option for the user to specify min/max number of selected checkboxes (also with validation) sounds good imo.

**Comment by SBoudrias** [comment]
@Srenky sounds good! Let's just make sure we split both features in different PRs (I'd start with adding `required`)
