### ISSUE TITLE
Prompts version of Checkbox no longer supports `loop`

### ISSUE THREAD

**Issue by jftanner** [SBoudrias/Inquirer.js#1283]
With the old `inquirer.prompt(questions)` approach, I tended to set `loop: false` on checkbox prompts because it gave a better UX for long lists.

Unfortunately, that that no longer seems to work with `@inquirer/prompts`. I notice it's not in [the documentation](https://github.com/SBoudrias/Inquirer.js/tree/master/packages/checkbox) either.

Is there any chance of getting that functionality back? Or was it removed for a reason?

**Comment by jftanner** [comment]
Digging into the code a little, it looks like the new paginator is always infinite, so this would apply to lists as well.

**Comment by SBoudrias** [comment]
Happy to get this feature back in. Not sure when I'll get to it, so let me know if you end up working on a PR.

**Comment by jftanner** [comment]
I would love to contribute but, unfortunately, I just don't foresee having the time. :/
If I do, I'll let you know!

Fortunately, it's not critical.

**Comment by artfuldev** [comment]
I'd love to pick this up!

**Comment by SBoudrias** [comment]
Thanks @artfuldev ! Let me know if you need support at any point.

**Comment by SBoudrias** [comment]
Hey @artfuldev, I assigned the issue to you.

There's a paginator in the new implementation, but it's been rewritten as a hook here https://github.com/SBoudrias/Inquirer.js/blob/master/packages/core/src/index.mts#L179-L219

So the idea would be to add the `loop: false` support there.

I'd ignore the pagination for `rawlist` & `expand` prompts (at least for now.) I didn't implement pagination in either in the new versions as it didn't seem necessary (and since those 2 prompts do not react to arrow keys, it just didn't seem to make sense to have pagination to start with.) So I'd say just focus on modifying the pagination hook and `select`/`checkbox`.

Adding tests for that new feature (I mainly care about tests in `select`/`checkbox`) would be great too to make sure it doesn't break in the future.

**Comment by artfuldev** [comment]
Oops, I seem to have completely missed that! Thank you so much for the direction. That helps a lot!
