### ISSUE TITLE
Support for bun.sh runtime

### ISSUE THREAD

**Issue by alec-c4** [SBoudrias/Inquirer.js#1302]
Hi!
I'd like to ask you about plans to add support for bun.sh runtime. I've tried checkbox example from docs and got

<img width="990" alt="SCR-20230911-pojz" src="https://github.com/SBoudrias/Inquirer.js/assets/25312/1cca6867-746d-46da-b7df-0420787fa8e2">

**Comment by SBoudrias** [comment]
Hi, this issue is known to bun https://github.com/oven-sh/bun/issues/4787

But please, do not open issues on all the open source projects you use for them to "support bun". Compatibility with Node is what Bun says it provides; so it's on the bun project to reach this milestone (not each project maintainers.) So open issues to bun, not us. Thanks!
