### ISSUE TITLE
What is the state of accessibility for this package?

### ISSUE THREAD

**Issue by JorensM** [SBoudrias/Inquirer.js#1309]
Hello, I want to make a console application, but I want to make it accessible. What is the state of accessibility for this package? How can I ensure that my console application is accessible, i.e is readable by screen readers? Thanks.

**Comment by SBoudrias** [comment]
What do you mean by "accessibility" in this case? To which extent, to what types of users, etc

Command line application are purely text based, so they're by default readable.

But they aren't semantic, so our choices of ASCII characters for controls will be read, but might not always be clear to someone relying on a screen reader (no concept of "select" components on a terminal; and no accessibility control to overlay them.)

Being text based, physical disabilities shouldn't be prevent usability. Font size is controlled by the terminal, so that'll accommodate short-sightedness. Color blindness related issues will depends on the user terminal color configuration; not something the Inquirer directly control or of which we get hints.

For some more color on the inherent limitations and challenges on screen-readers on command line app: https://tspivey.wordpress.com/2007/11/14/my-thoughts-on-the-current-state-of-command-line-accessibility/

**Comment by JorensM** [comment]
@SBoudrias Thanks for your response and for the linked post. My main interest with command-line accessibility is with screen readers. To not diverge the topic from the theme of this package, I'd like to know particularly how to handle screen readers in regards to the input prompts that this package offers. For example, how would one go about making sure that screen readers correctly understand that a list of options is a list of options that can be selected, and not just a list of items that are not interactive? Thanks.

**Comment by SBoudrias** [comment]
Command lines unlike browser do not have an accessibility tree. So the strict answer is no. But that doesn't mean it'll be unusable for all users, there's a lot of nuances.

If you find any issues with you users, I'm happy to review specifics or suggestions to improve.
