### ISSUE TITLE
Input error at isEnterKey

### ISSUE THREAD

**Issue by Eric-South** [SBoudrias/Inquirer.js#1312]
I am trying to integrate Inquirer into a CLI project, and am unable to get the most basic of examples working. 
Node version is 14.19.0. Running this in windows.
I've set up inquirer in an empty project with the following steps:
npm init
npm install @inquirer/prompts
update package.json with "type": "module"
npm run index.js with the following contents:

```
import { input } from '@inquirer/prompts';

const name = await input({ message: 'Enter your name' });
```

and receive the following error every time a key is pressed. 
```
Enter your name  (node:10196) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at isEnterKey
```

I've tried multiple terminals and can't seem to get this to work.

**Comment by SBoudrias** [comment]
Hi, I'll need more information to be able tom help since I'm unable to reproduce it.

Did you try running `npx @inquirer/demo@latest` - do you see the same issue when running the input prompt demo?

- Which version of `@inquirer/prompts` are you using? Did you try latest?
- What's your Windows' version?
- What's the terminals you tried this on?

**Comment by UNDERCOVERj** [comment]
I meet too

**Comment by UNDERCOVERj** [comment]
I use mac termial run `npx @inquirer/demo@latest`，meet the same error

**Comment by UNDERCOVERj** [comment]
> I use mac termial run `npx @inquirer/demo@latest`，meet the same error

nodejs v14 meet the error, but node v16 not meet the error

**Comment by SBoudrias** [comment]
Oh... I see. I can reproduce with Node 14.

Do note that [Node 14 and 16 are both EOL](https://github.com/nodejs/release#end-of-life-releases). As such, we're not maintaining backward compatibility with either.

If you cannot update to an LTS version of Node (and you really, really, should), then the only solution is to rely on old versions on Inquirer released while the version you used were still in LTS status.

Since Node 14 went EOL in April, do note no version of `@inquirer/prompts` will officially support it since that package was release after. In which case you'd fallback to the `inquirer` package; around `9.1.0`.
