### ISSUE TITLE
Removed type causing breaking change in non-major update.

### ISSUE THREAD

**Issue by yhaskell** [SBoudrias/Inquirer.js#1345]
Hi and thanks for the amazing project ;)

I have found, that in this commit https://github.com/SBoudrias/Inquirer.js/commit/3a9adcfedbd302959f1cd37f7de969eead6fa410
there was a change to hide the type that was previously available. 

It was a nice type to use in functions, that also causes quite a lot of inconvenience:

```ts
// fix for the type being hidden
type Choice<T> = Exclude<Parameters<typeof select<T>>[0]["choices"][number], Separator>;
```

And, as it was updated without raising the major version, auto-update caused the breaking change.

Can you please share, why the type was hidden?
And possibly re-export it again?

**Comment by SBoudrias** [comment]
Hi @yhaskell, this project being widely use, I want to keep the interface minimal to prevent issues such as that one you just ran into. In my experience, I found underlying types implementation to change often to account for accrued inference or reactivity to the types being passed in. In other words, while the interface of a prompt will not often have breaking changes, reviewing how the `Choice` type is defined is much more likely.

Because of this, I strongly prefer to not expose them in order to not accrue the amount of major version/breaking changes going out. Those make migration harder and we leaves folks behind on old version too easily.

Prefer reaching out to the underlying type with type accessors; like `Parameters<typeof prompt>[0]['choices'][number]` (pseudo-coding, but you'll get the idea.)
