### ISSUE TITLE
Remove overflow message when list is scrolled

### ISSUE THREAD

**Issue by sindresorhus** [SBoudrias/Inquirer.js#147]
re https://github.com/SBoudrias/Inquirer.js/pull/146

Would be nice if the "move up and down" message disappeared when the user started moving up or down.

**Comment by GeorgeGkas** [comment]
Let's make a little investigation.

*Before I start, keep in mind that the list types (`list`, `rawlist`, `expand` and `checkbox`) work as [Circular Buffer](https://en.wikipedia.org/wiki/Circular_buffer).*

@dylang I believe this does not cause so much trouble.

Let's start with an example. The [long-list.js](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/examples/long-list.js) example suits fine. The list starts circling when the user press the up key at first keypress or after 3 down keypresses. The message `(Move up and down to reveal more choices)` does a good job denoting that there are choices that are hidden. This message is shown only in large lists (or lists that exceed [`pageSize`](https://github.com/SBoudrias/Inquirer.js#question)) which is a good thing because it does not add visual noise for small lists. For me this is the simplest usable UI.

@sindresorhus I cannot think something better for the UI that will be less verbose and offer the same level of usability. Of course we can investigate the idea of @dylang more, but the current implementation (as Circular Buffer) makes the things more complex in terms of UX.

Suppose we agree to work in the idea of @dylang (which I personally find quite attractive). With the current implementation we have to answer the following: What exactly does the number in the `6 more choices` indicate?

Consider the following edge example. A list with 8 elements of `pageSize` equal to 3.

![prompt example](https://sketch.io/render/sk-f2416ec07cbdaf7330dd45b680a7a927.jpeg)

- If `more choices` denote the choices from the current answer **3** then (because the nature of the list allows circling) both `▼` and `▲` will contain the same number (which is **7**). 

- If `more choices` denotes the number of elements that exceed the current [`pageSize`](https://github.com/SBoudrias/Inquirer.js#question) then both `▼` and `▲` will contain the same number (which is **5**). 

Of course this edge case was created to show that  both `▼` and `▲` can contain the same number of elements. But this does not make the solution more acceptable, in terms of UX, if the number of items where distinct values either. We would have to increase the `▼`  and decrease the `▲`  (or vice versa) every time the user pressed up or bottom arrow key.

A solution like this would be good enough to be implemented if the list was linear.

**Final Thoughts**
This issue was created 4 years ago. Until now, this package was used in thousands of projects and downloaded millions of times. I believe that if this issue was critical, there would be complains regarding this feature. But this is not the case and this issue is inactive since then. If there are no more comments, then @SBoudrias you can close it.

**Comment by SBoudrias** [comment]
I'm going through old issues trying to close some. The list prompts now all expose a `theme.helpMode` configuration option that can be set to `never` or `always` to show/hide them; by default it's `auto` which is the current "smart" behaviour.
