### ISSUE TITLE
instanceof always returning false when checking for ExitPrompError errors

### ISSUE THREAD

**Issue by codePassion-dot** [SBoudrias/Inquirer.js#1475]
- I'm trying to check if an error thrown by inquirer is an instance of ExitPromptError (user press Ctrl+c) so that I can gracefully shutdown the program but for some reason error instanceof ExitPromptError is always returning false. I'm importing the class from @inquirer/core package. and this is happening with input from @inquirer/input package.

**Comment by SBoudrias** [comment]
Any chance you're using a build tool that might not reuse the exact same file? `instanceof` checks are always pretty brittle with JavaScript.

**Comment by wardxela** [comment]
Same error. Pretty strange thing

**Comment by SBoudrias** [comment]
I don't think that's likely.

**Comment by wardxela** [comment]
I've analyzed the code that is being generated by my build tool (I use `tsup` btw) and looks like whenever I try to import something from `@inquirer/core` myself, `tsup` will bundle it instead of importing. Thus I end up with two different classes.

The following code:

```js
import { ExitPromptError } from '@inquirer/core'
```

Converts to this:

```js
// ../../node_modules/@inquirer/core/dist/esm/lib/errors.mjs
var ExitPromptError = class extends Error {
};
```

Referring to `tsup` [documentation](https://tsup.egoist.dev/#excluding-all-packages), it should automatically skip bundling all packages, that **listed** in `package.json`.

So in order to fix the issue, I just needed to install `@inquirer/core` explicitly in my app:

```bash
npm i @inquirer/core
```

P.S. Thank you for your awesome project!

**Comment by SBoudrias** [comment]
It's usually best to not rely on `instanceof` at all for any projects using a bundler. Due to how bundlers work, there's many many scenarios into which it'll fail.

I'll define the `name` property of all errors (which I see are missing now.)

So you going forward, I would recommend using the following pattern:

```diff
- if (error instanceof ExitPromptError) {
+ if (error.name === 'ExitPromptError') {
```
