### ISSUE TITLE
Inquirer: checkbox doesn't provide `default` support.

### ISSUE THREAD

**Issue by mshima** [SBoudrias/Inquirer.js#1626]
New checkbox supports `checked` property inside choices but not a `default` value in config.
`string` choices was added as alternative to object choices due to compatibility but it's not compatible with providing a custom checked value.

I think there are 2 approaches that can be considered:
- convert to choices object (including checked with defaults) in inquirer compatibility layer. This keeps core prompts more simple.
- add default support to checkboxes.

We will probably need to use approach 2 due to shared types.

**Comment by SBoudrias** [comment]
Are you asking because it'll be a downstream breaking change on Yeoman?

My preferred approach is to add a compatibility layer in `inquirer` and leave the checkbox prompt untouched.

That being said, it's a fairly minor and maybe rarely used option, I'd question the need to go out of our way to maintain that interface compatibility given there's 1) still a way to achieve the same feature, and 2) it won't crash a generator.

**Comment by mshima** [comment]
> Are you asking because it'll be a downstream breaking change on Yeoman?

Yes.

> My preferred approach is to add a compatibility layer in `inquirer` and leave the checkbox prompt untouched.

Ok to me.

> That being said, it's a fairly minor and maybe rarely used option, I'd question the need to go out of our way to maintain that interface compatibility given there's 1) still a way to achieve the same feature, and 2) it won't crash a generator.

The issue can be handled in yeoman side too.
Since you did a great job in providing inquirer compatibility, the chance will be at least documented.
