### ISSUE TITLE
access anwsers in validate callback

### ISSUE THREAD

**Issue by wayou** [SBoudrias/Inquirer.js#198]
is it possible to retrieve the answers within the validate callback?

the scenario is that i wanna validate an input by the previous answers.

**Comment by MohamadAtieh** [comment]
+1
My case is that I want to validate the current answer **if and only if** a previous answer was given. The line [here](https://github.com/MohamadAtieh/MineTwitter/blob/master/miner.js#L65) - based on [this one](https://github.com/MohamadAtieh/MineTwitter/blob/master/miner.js#L42)

**Comment by himynameisdave** [comment]
+1
This should really exist already && I have the same concern as @MohamadAtieh. My current workaround is to have two sets of prompts (synchronous), the second one based on the results of the first set. It feels ugly && this is a *bad UX* for people using [my yeoman generator](https://github.com/himynameisdave/eggs-genny).

**Comment by mischah** [comment]
:+1: 

Would love to have that. My use case:
I have [prompts](https://github.com/micromata/generator-bootstrap-kickstart/blob/develop/app/index.js#L63-L88) to name directories and feel the need to validate against already given answers to prevent naming directories the same. Because that would mess things up badly.

@himynameisdave 
It seems that »someone« has to send a PR according to the [tweet](https://twitter.com/Vaxilart/status/555074141099790336) of @SBoudrias :octocat: 

I’m already digging into the sources of Inquirer.js, but I’m not convinced that I can handle that.

**Comment by himynameisdave** [comment]
I sort of overexaggerated the bad UX thing. It *works* but its just to me as the developer it looks sloppy/I wish there was a cleaner way to do it. To the user it pretty much does what you need.

**Comment by SBoudrias** [comment]
The key line is this one: https://github.com/SBoudrias/Inquirer.js/blob/e146441bb83f565801fd31db53cb4f30044fbf8b/lib/prompts/base.js#L151

The answers are passed to the constructor, so they should be available at that point.

**Comment by mischah** [comment]
@SBoudrias 

Thanks for the hint. But it seems that I’m not advanced enough in JS architecture to implement that.

Would you accept a PR providing an example and the test and you take care of the implementation within `/prompts/base.js`?

Just in the case, that no one else is willing to send a PR dealing with the whole thing. :smirk:

**Comment by SBoudrias** [comment]
Yes, that would be a good/helpful first step

**Comment by MohamadAtieh** [comment]
I think if we can pass the `answers` object to `validate` just like `when`, somehow, then that would be it.

Having `validate` to accept either one or two parameters, making the first one the input value (required) and second (optional) parameter be the `answers`object? Is that a possible?

**Comment by pigulla** [comment]
+1 for this!
