### ISSUE TITLE
JSON Schema Inquirer

### ISSUE THREAD

**Issue by gobwas** [SBoudrias/Inquirer.js#248]
Hi there!

Thank you very much for your library :beers:!
At some project I wanted to use some universal validation rules for prompt, and not found any better way than to use JSON Schema. So, [I wrote simple library](https://github.com/gobwas/schinquirer) based on yours, and, also, on `is-my-json-valid` json-schema validator.

If you want, you can link it in your readme or smth, to get your users know of this little feature.

Thank you!

**Comment by SBoudrias** [comment]
Hey, thanks for letting me know. I'm always interested to see what other people build on top of inquirer - or projects just inspired by it.

**Comment by adius** [comment]
@SBoudrias I feel like this should be part of inquirer. Did you ever think of making this a first class feature?

**Comment by SBoudrias** [comment]
No, I don't think that's something most users would needs.

Also, if you want to pass JSON in, almost everything will work, excepts  validate/filter and other functions versions of properties.

**Comment by adius** [comment]
> Also, if you want to pass JSON in, almost everything will work, excepts validate/filter and other functions versions of properties.

I'm not sure if you really know what JSON schema is all about.
It's not about that it uses JSON (you can use plain js objects or YAML just as well)
It's about specifying what object you want to have in the end instead of which questions to ask.
This would enable cool stuff like this:

Schema:

```json
{
  title: "Person",
  type: "object",
  properties: {
    favorite_color: {
      type: "string",
      format: "color",
      title: "favorite color",
      default: "#ffa500"
  },
  …
}
```

So instead of specifying that inquirer shall ask for the red, green and blue value of a color,
you just say that you want to have a color in the end and inquirer automatically knows what to do.

e.g.

```
? Favorite Color:
  ? red 54
  ? green 232
  ? blue 49
```

This would also be great for dates, contacts, … and all kind of other custom data types.

Furthemore it's reusable. Maybe you want to create the same objects via an web-interface.
Then you can simply reuse your JSON schema like this http://jeremydorn.com/json-editor

**Comment by adius** [comment]
This is also a great resource to learn about JSON schema: http://spacetelescope.github.io/understanding-json-schema

**Comment by gobwas** [comment]
@adius 👍
