### ISSUE TITLE
Weird behavior on Windows 8.1

### ISSUE THREAD

**Issue by mkorakakis** [SBoudrias/Inquirer.js#262]
Hello,

If somehow the input takes more that one line, for each newline that I use the message seems to reappear along with it. Same thing if i try to paste a long line. Gets even more buggy if i try to delete the text. Similar to [#214](https://github.com/SBoudrias/Inquirer.js/issues/214) and [#249](https://github.com/SBoudrias/Inquirer.js/issues/249).

Example:
![example](http://s22.postimg.org/d411mgnf5/Capture.png)

**Comment by SBoudrias** [comment]
Which version are you using?

**Comment by mkorakakis** [comment]
The latest 0.9.0

**Comment by martinheidegger** [comment]
Note: this is a bug in early Node 4 & 5 versions. Should be fixed now.

**Comment by SBoudrias** [comment]
Yeah, please retry on the latest version. This should be fixed.

**Comment by jokeyrhyme** [comment]
If this is related to https://github.com/nodejs/node/issues/5384 then I have a module that helps identify broken versions of Node:

- https://github.com/jokeyrhyme/is-node-interactive-tty-broken

Do you think it might be worth integrating a similar check into this library? So that a warning or something could be displayed? Or perhaps modifying the "engines" part of package.json to help avoid broken Node versions at installation time?
