### ISSUE TITLE
[feature request] Up arrow for last result

### ISSUE THREAD

**Issue by drj-io** [SBoudrias/Inquirer.js#306]
Up arrow for last answer.  Great for setting up builds and configurations.

This could be a configurable option.

**Comment by mhkeller** [comment]
I think this could work by modifying the [input](https://github.com/SBoudrias/Inquirer.js/blob/master/lib/prompts/input.js) prompt type to fill in the `default` value. 

The use case I'm envisioning is you want to use the default string as a starting point. For example, you have a date `2016-05-01` as the default and you want it to change it to `2015-05-02`. You could up-arrow and change only the last character.

If what you're thinking is that inquirer should remember your last values, I think that belongs in whatever application you're building. I've done this usually by writing out the answers object to a file and then dynamically populating `default` fields with those values for new sessions.

Because inquirer supports custom prompt types, I'm going to take a crack at adding that functionality using `input` as a jumping off point.

**Comment by mhkeller** [comment]
I've got a basic version working here: https://github.com/mhkeller/inquirer-input-up

Having some trouble with the cursor position though that would be great to get some help on: https://github.com/mhkeller/inquirer-input-up/issues/1

**Comment by allenhwkim** [comment]
How about up/down arrow keys to navigate through the last answers  only for `input` prompt?

I am recently buildnig a command line interface to accept commands which are repeating often.

This feature will make  more like unix command line.

If it's ok with the owner, I can make PR for either;

 1. modify `input` prompt to store/load the last input here, https://github.com/SBoudrias/Inquirer.js/blob/master/lib/prompts/input.js#L102

2. or, create a new `command` promote copied from `input` prompt.

**Comment by SBoudrias** [comment]
@allenhwkim how about a custom prompt plugin?

**Comment by allenhwkim** [comment]
@SBoudrias yes I can use a custom prompt. However, IMO, I think it's better to be a core feature. It's up to you.

**Comment by allenhwkim** [comment]
For those who is interested in solution to build a `command` prompt extended from `input` prompt. First install `preferences` to save command history

`npm install preferences --save`

**`src/inquirer-command-prompt.js`**
```
/**
 * `command` type prompt
 * It works the same as `input` type prompt, plus;
 *
 *  1. It auto fill commands when UP/DOWN arrow is pressed
 *  2. It auto fill commands when TAB is entered
 *  3. It saves the history to ~/.config/preferences
 */
var util = require('util');
var InputPrompt = require('inquirer/lib/prompts/input');
var Preferences = require('preferences');

var commands = new Preferences('inquirer-command', { history: [] });
var numCommandsHistory = commands.history.length;
var currentNdx = numCommandsHistory;

module.exports = CommandPrompt;

function CommandPrompt() {
  return InputPrompt.apply(this, arguments);
}
util.inherits(CommandPrompt, InputPrompt);

CommandPrompt.prototype.onKeypress = function (e) {
  /** go up commands history */
  if (e.key.name === 'up') {
    currentNdx--;
    (currentNdx < 0) && (currentNdx += numCommandsHistory); //prevents negative value
    this.rl.line = commands.history[currentNdx % numCommandsHistory];
    this.rl.write(null, {ctrl: true, name: 'e'});
  }
  /** go down commands history */
  else if (e.key.name === 'down') {
    currentNdx++;
    this.rl.line = commands.history[currentNdx % numCommandsHistory];
    this.rl.write(null, {ctrl: true, name: 'e'});
  }
  /** search for matching history */
  else if (e.key.name === 'tab') {
    var matchingHistory = commands.history.find(el => {
      return el.match(new RegExp(`^${this.rl.line.replace(/\t/,'')}`));
    });
    if (matchingHistory) {
      this.rl.line = matchingHistory;
      this.rl.write(null, {ctrl: true, name: 'e'});
    }
  }
  this.render();
};

```

**Usage**
```
var InquirerCommandPrompot = require('./src/inquirer-command-prompt');
inquirer.registerPrompt('command', InquirerCommandPrompt);
...
  inquirer.prompt([{
    name: 'my-command',
    type: 'command',
    message: '>', 
    validate: function(command) {
      return true; 
    }
  }]).then( function(answers) {
  ...
  })
```

I was almost close to submit a PR for this feature, but I did not because I wasn't not sure of owner's willingness to accept it.

**Comment by SBoudrias** [comment]
@allenhwkim feel free to publish this custom prompt to npm so other people can use it in their own projects!

**Comment by heylookltsme** [comment]
@allenhwkim +1 for publishing this to npm! This is exactly what I was looking for.

**Comment by heylookltsme** [comment]
@allenhwkim fwiw I just tried implementing this and I'm running into readline issues - 
```
TypeError: Cannot read property 'substring' of undefined
    at Interface._getCursorPos (readline.js:651:49)
    at Interface._moveCursor (readline.js:671:21)
    at Interface._ttyWrite (readline.js:761:14)
    at Interface.write (readline.js:344:24)
```

See: https://github.com/SBoudrias/Inquirer.js/issues/272 and https://github.com/nodejs/node/issues/3006

**Comment by allenhwkim** [comment]
@heylookltsme 
Interesting. I don't have that issue(because I do not use Windows?).

I am using this for my webtest module, and it works without problem.
Please copy/paste code if these are helpful.

https://github.com/allenhwkim/webtest/blob/master/src/inquirer-command-prompt.js
https://github.com/allenhwkim/webtest/blob/master/index.js#L54

**Comment by heylookltsme** [comment]
Oh I'm not on Windows either. I use a Mac.  

What version of inquirer are you using? I'm wondering if maybe this prompt broke with a later version.

Also, I realized I was using the integrated terminal in my IDE, so maybe that had something to do with it.

**Comment by allenhwkim** [comment]
@heylookltsme yes it's possible. I only use iTerm2 or built-in terminal.  [WebTest](https://github.com/allenhwkim/webtest) is using inquirer 1.2 as you see at package.json https://github.com/allenhwkim/webtest/blob/master/package.json#L19

**Comment by sullof** [comment]
@allenhwkim I have the same problem. It would be great if you fix this issue and publish it on npm.

**Comment by sullof** [comment]
@allenhwkim If for you it's fine, I can fix the prompt and publish it to npm — when I have time :-)

**Comment by allenhwkim** [comment]
@sullof I am fine with it

**Comment by sullof** [comment]
Great, thanks. I fixed it and I am adding a few more features (like context-based histories, dynamic autocomplete, etc.). I will let you know.

**Comment by sullof** [comment]
@SBoudrias @allenhwkim @heylookltsme 
I have published the prompt on npm (https://www.npmjs.com/package/inquirer-command-prompt). 

As you can see on Github (https://github.com/sullof/inquirer-command-prompt) I haven't set any tests yet. I will do it asap. Though, I am actively using this prompt in a project and I can say that everything works as expected. Let me know.

**Comment by SBoudrias** [comment]
@sullof I'll be happy to list it in the README plugin list. Send a PR when you feel it's ready.
