### ISSUE TITLE
Question: Parsing `input` string as json but display string to user

### ISSUE THREAD

**Issue by mhkeller** [SBoudrias/Inquirer.js#349]
I have an `input` type prompt that asks for a list of names that could be parsed as json according to some convention such as being comma-delimited, e.g. `Name one, Name two` etc. I would like to use to `filter` function to turn these into a list.

The problem, though, is this displas `[Object object], [Object object]` to the user even though I would prefer it to return the original string the user entered. 

I could parse the answers once the user is finished, but I would prefer to put this logic into the question prompt so they could be used more modularly. 

Any thoughts on whether this is possible? Is there a way to use a similar `name`, `value`, `short` convention like in `choices`?

**Comment by SBoudrias** [comment]
This being quite an edge case, I feel like we shouldn't add further API surface to fix it.

That being said, you should approach this problem from the JS perspective. Your issue is how the objects you create get stringified.

As so, just define a custom `toString()` method on the object you return from your filter function, and it'll fix your output :)

**Comment by mhkeller** [comment]
Thanks. That does the trick.
