### ISSUE TITLE
Allow programmatic re-rendering

### ISSUE THREAD

**Issue by SBoudrias** [SBoudrias/Inquirer.js#46]
Related use case: https://github.com/yeoman/yo/pull/57

**Comment by GeorgeGkas** [comment]
@SBoudrias 

This issue was created 3 years ago. This was being addressed in #289, but @dthree canceled it. The proposed API was implemented in [Vorpal](https://github.com/dthree/vorpal) as I read on https://github.com/SBoudrias/Inquirer.js/pull/289#issuecomment-145107571, but not addressed at Inquirer in that time.

The current version of Inquirer (6.2.0 as seen in [package.json](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/package.json#L3)) gives the option through [Reactive Interface](https://github.com/SBoudrias/Inquirer.js#reactive-interface) to dynamically  handle question prompts. Is that the case we tried to accomplish when the issue was first introduced? If that's that case we can safety close this issue, else more investigation has to been done.

**Comment by SBoudrias** [comment]
Hum, we never really implemented this in core. I think it's fair to close it as there's no plan to make this work right now - and I don't think there's an easy win here.

Maybe if we ever get done with the refactor idea then it'd be a good time to revisit.
