### ISSUE TITLE
prompt() fails silently if stdin isn't a TTY

### ISSUE THREAD

**Issue by also** [SBoudrias/Inquirer.js#495]
When run with `node test.js < /dev/null`, this script exits with code 0 and without logging anything:

```javascript
var inquirer = require('inquirer');

inquirer.prompt([{name: 'username', message: 'username'}])
.then(
    function (answers) {
      console.log('Answers:');
      console.log(answers);
  },
  function (err) {
    console.log('Error:');
    console.log(err.stack);
    process.exit(1);
  }
);
```

This can cause some weird problems in CI environments, where scripts succeed without doing anything.

I encountered this with inquirer 3.0.1 on Node.js 6.9.1.

**Comment by SBoudrias** [comment]
We could probably add a check and reject the promise in non-TTY. PR welcomed.

**Comment by nelsonpecora** [comment]
Might this issue also cause inquirer prompts to silently fail when calling [`get-stdin`](https://github.com/sindresorhus/get-stdin) before instantiating inquirer? That's what I'm seeing on a project, but I don't know enough about stdin/tty to figure it out.

**Comment by sguillia** [comment]
Hi!

This issue is still happening with latest version 8.2.0

Documentation states that `prompt() will return a rejected promise with an error`

It does not because, likely because `skipTTYChecks` defaults to true

Why was this behavior reverted without changing the documentation? Or why was it reverted at all?

Is it possible to set `skipTTYChecks` to true by default, or to make it return default values?

Thanks
