### ISSUE TITLE
Auto answering

### ISSUE THREAD

**Issue by likerRr** [SBoudrias/Inquirer.js#517]
Is it possible to automatically answer the question? E.g. when user calls cli app with arguments I want to parse them and depending on their values automatically answer a question when it's asksed. 

So I would like to write something like this:

```javascript
const askName = {
  type: 'input',
  name: 'name',
  message: `What's your name?`,
  // auto also can be string/boolean any other valid type
  auto: session => process.argv.name ? process.argv.name : undefined
};
```

So if `auto`'s value is undefined, then the answer is prompted to user otherwise the answer automatically sets to returned from callback value.

It's nice to have this ability rather then don't ask the question at all because user can see the answer that was choosen by his actions (in my case by calling cli app with some arguments).

I tried to achieve such behavior from manually calling `prompt.ui.rl.emit('line', 'hello')` but I can't find sutable callback in inquirer's life cycle where I can do this.

**Comment by sholladay** [comment]
Absolutely. This is a great pattern in [Yeoman](http://yeoman.io/) generators like [generator-seth](https://github.com/sholladay/generator-seth), so I will use that as an example.

Steps:
1. [Get a command line argument](https://github.com/sholladay/generator-seth/blob/acb0f92fb4da5ca03877db90220a25d089028fc9/app/index.js#L60).
2. [Dynamically show/hide a prompt](https://github.com/sholladay/generator-seth/blob/acb0f92fb4da5ca03877db90220a25d089028fc9/app/index.js#L136) based on whether the argument was provided.
3. [Merge the arguments and prompt answers](https://github.com/sholladay/generator-seth/blob/acb0f92fb4da5ca03877db90220a25d089028fc9/app/index.js#L200) with something like `Object.assign()`.

The linked example uses some Yeoman APIs for dealing with arguments, but could be refactored pretty easily. I would use [meow](https://github.com/sindresorhus/meow) for this in a standalone CLI.

This approach is quite flexible. For example, instead of skipping the prompt when the user has provided an argument, you could still show the prompt but make their argument the default value, which would be shown to them and behave kind of like a confirmation screen. To do this, you would pass the argument to `default` instead of `when`.

**Comment by likerRr** [comment]
@sholladay thank you for explanation, but unfortunatelly it's not what I'm looking for. 

You was right when you mentioned that my case bit different. I want to skip the confirmation step for the questions with `auto` property, because when I call my app with some argument which sets default answers on questions I don't want confirm it for the each question. Imagine, that I have 100 of questions. I just want to fill in them once and other day just generate without prompting them once again, even with default values set as for previous time.

Also I don't want return false as `when` value, because I want to see which answers were set (automatically) for which question.

Have you got the idea?

**Comment by SBoudrias** [comment]
Maybe would could print yourself the values in the when function:

```js
when: function () {
    if (options.foo) {
        console.log('? My question is:' + chalk.cyan(options.foo));
        return false;
    }
    return true;
}
```

**Comment by sholladay** [comment]
> Have you got the idea?

I think so, we'll see. 😄  

Let me revisit what you mean by "default" and "automatically answer the question." In Inquirer, the term "default" really means "initial value", similar to `defaultValue` on an [input element](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) in the DOM. If the prompt is not shown due to using `when: false`, then the `default` is not used.

> I don't want confirm it for the each question

Okay, so it sounds like you don't want to prompt for a question at all if we receive a value for it via a command line argument. This is what `when` does in my example earlier.

If you do use `when: false`, then there won't be any answer in the object returned by Inquirer. This is why I use `Object.assign()` to merge the command line arguments and the Inquirer answers.

> I just want to fill in them once and other day just generate without prompting them once again

Ah, okay. This sounds like what `store: true` does in Yeoman. This in not part of Inquirer, but could be added to your app by using [conf](https://github.com/sindresorhus/conf) to persist the answers. You would attempt to load existing configuration and use those values instead of prompting for them.

> I don't want return false as `when` value, because I want to see which answers were set (automatically) for which question.

So you want to show the user what value is implicitly being used but not let them change it? This sounds like bad UX to me, honestly. And yeah, you can just use `console.log()` as @SBoudrias described. At that point it's not a prompt, it's just a log.

**Comment by likerRr** [comment]
So, I found [the code](https://github.com/SBoudrias/Inquirer.js/blob/master/lib/prompts/base.js#L128) which generates question output line and as @SBoudrias said modified code a little:

```javascript
const PromptBase = require('inquirer/lib/prompts/base');

function autoAnswer(question) {
  // since console.log() returns undefined, we can use such one-liner
  question.when = () => console.log(new PromptBase(askName).getQuestion());

  return question;
}

const askName = {
  type: 'input',
  name: 'name',
  message: `What's your name?`,
  default: 'Anonymous'
};

// now the question is "auto answering" and output remains native
autoAnswer(askName);
```

What do you think? Is it safe to use internal function from here `inquirer/lib/prompts/base` ?

**Comment by likerRr** [comment]
But probably it's better to use other color to let the user know, that particular question was answered not usual way.

**Comment by leebenson** [comment]
I need this too.

I'm building a CLI tool that takes options via yargs. Inquirer is used to show a 'wizard' for any question that isn't already answered by a command line arg.

I can't use `default`, because that's basically just echoing back what the user has already entered, and is asking them to re-confirm.

I can't use `when()`, because that will skip the question entirely and avoid populating the answers hash for further questions, as well as miss out on the validation functions.

What would solve it is an `answer` field on the question object. Unlike 'default', putting a value there would avoid asking the question - BUT, it would automatically re-ask it if the value fails validations and show the usual error prompt.

So, it's basically a means to skip asking the question, but treat the value given as the answer.

Does that make sense?

**Comment by AdrienHorgnies** [comment]
I've came with a workaround. Maybe it can help someone.
The idea is that I have two information source : a configuration file (could be whatever object your want) and `inquirer.prompt`.
1. I load the configuration file and validate values using `question.validate` functions.
2. Depending what's is defined in the configuration file, I set related `question.when` to false.
3. I run every `question.default` on the configuration values and replaces default with output if any. That is because skipping questions doesn't populate the answers as explained above.
:
```javascript
// Here prompt is my own.
prompt.init() // init load configuration file
    .then(config => prompt.askCredentials() // asking information
        .then(answers => Object.assign(config, answers)) // merging
    )
```

```javascript
/**
 * load configuration file if present
 * make related prompts to be skipped
 *
 * @resolves configuration object
 */
const init = () => fse.readJson('.db-config.json') // todo use constant
    .then((config) => {
        // disable prompts for provided items
        lodash.forEach(config, (value, key) => {
            if (inquiries[key]) {
                // I am so sorry, I have no other choice than to compare to true
                // validate returns true or the error message and a non empty string is considered truthy
                if (typeof (inquiries[key].validate) === 'function' && inquiries[key].validate(config[key]) !== true) {
                    // better store all errors then log them all
                    throw Error(`.db-config.json "${key}": "${value}" ${inquiries[key].validate(config[key])}`);
                }
                inquiries[key].when = false;
            } else {
                // todo more something of a warning
                throw Error(`${inquiries[key]} is defined in .db-config.json but is not a valid configuration item`); // todo use constant
            }
        });
        lodash.forEach(inquiries, (prompt) => {
            if (typeof (prompt.default) === 'function') {
                // if prompt can define a default value from configuration, uses it
                if (prompt.default(config)) prompt.default = prompt.default(config);
            }
        });
        return config;
    })
    .catch((error) => {
        console.error(error);
        return {};
    });

const askCredentials = () => inquirer.prompt([
    inquiries.dbms,
    inquiries.host,
    inquiries.port,
    inquiries.user,
    inquiries.password,
    inquiries.schema
]);
```
If you want more details, [the source is here](https://github.com/bastienmichaux/db-importer).

**Comment by karlhorky** [comment]
What I ended up doing was a variation on @SBoudrias's comment https://github.com/SBoudrias/Inquirer.js/issues/517#issuecomment-288964496 which sets the answer to an arbitrary value and tells the user that the answer was set to a specific value for a specific question.

```js
const bar = 'BAR';

const askName = {
  type: 'input',
  name: 'name',
  message: `What's your name?`,
  when(answers) {
    if (foo) {
      console.log(`${chalk.blue('!')} Setting answer to "${bar}" for "${this.message}"`);
      answers.name = bar;
      return false;
    }
    return true;
  },
}
```

cc @likerRr @leebenson does this work for you?

**Comment by karlhorky** [comment]
Ah I've found out that an array of questions with `when`s that always return false just returns an empty object 😕 

@SBoudrias would you be up for changing this behavior to not discard the mutated `answers` value? I've opened PR #645 with a failing test.

To demonstrate what I'm looking for, another (simpler) example of what I hope to get working:

```js
// NOTE: Not working currently, don't use :)
var prompts = [
  {
    type: 'confirm',
    name: 'q1',
    message: 'message',
    when: function(answers) {
      answers.q1 = 'foo';
      return false;
    }
  },
  {
    type: 'confirm',
    name: 'q2',
    message: 'message',
    when: function(answers) {
      answers.q2 = 'bar';
      return false;
    }
  }
];

inquirer.prompt(prompts);
```

**Comment by SBoudrias** [comment]
I'm not super warm to the idea of allowing users mutate the answers object. That's usually a pretty bad design decision.

Why not just provide defaults? `Object.assign({ q2: 'bar' }, answers)`?

**Comment by karlhorky** [comment]
Defaults would almost work, but they are not great for the following reasons:

1. They happen outside of the sequence of the prompt. This is sub-ideal because:
    - They are outside of the validation logic
    - The assignment to the final answers object happens at a different time. Because of this, notifying users that a default value has been assigned needs to happen out of sequence (e.g. after the rest of the prompts).

2. This moves some of the sources of the answers outside of the questions list, which makes it one more place to look. I like to think of `prompt()` kind of like `Array.prototype.reduce()`, taking in the questions list and providing answers at the end. I'd like to keep all of the logic within the questions if possible. I'm using (and can envision continuing to use) `when()` kind of like a callback function to `reduce()`, except that every question has its own separate callback.

--- 

> I'm not super warm to the idea of allowing users mutate the answers object. That's usually a pretty bad design decision.

Regarding this, I agree with you from an idealistic perspective (immutability improves comprehensibility and debuggability) and I would greatly prefer a way to achieve my goals without having to mutate `answers`.

So if there's a different way of achieving something similar (other than modifying the `answers` outside of the questions objects), I'm all ears. Here's another illustration of the complex sequence I'm trying to do:

**Simplified example:**

```js
const options = await getArgsOrConfig();
const allCustomers = await getAllCustomers(token);

const prompts = [
  {
    type: 'list',
    name: 'customer',
    message: 'Customer:',
    choices: allCustomers,
    when(answers) {
      if (options.customer) {
        console.log(`${blue('!')} Using "customer" option from arguments or config`);
        answers[customer] = options.customer;
      } else if (allCustomers.length === 1) {
        const firstCustomer = allCustomers[0];
        clog(`${blue('!')} Using only authorized customer "${firstCustomer.name}"`);
        answers.customer = firstCustomer.value;
      } else {
        // Prompt for input
        return true;
      }
    },
  },
  {
    type: 'input',
    name: 'git_url',
    message: 'Git URL:',
    validate: input =>
      /(github\.com|bitbucket\.org|gitlab\.com|\.git$)/.test(input) ||
      'Please enter a valid Git URL.',
    when(answers) {
      if (options.git_url) {
        console.log(`${blue('!')} Using "git_url" option from arguments or config`);
        answers[git_url] = options.git_url;
      } else {
        // Prompt for input
        return true;
      }
    },
  }
];

inquirer.prompt(prompts);
```

**Full code:** https://github.com/amazeeio/lagoon/blob/a4a6fa7f101243a69676f060c6c5d8ddaa403ccd/cli/src/commands/projectCommands/create.js#L123-L222

**Comment by karlhorky** [comment]
@SBoudrias Would you be up for alternately extending `when()` to allow for a different, non-boolean return type? Where you return either one of:

* a value for the current answer
* a new `answers` object to replace the current one with (kind of similar API to `reduce()` callbacks?)

**Comment by sholladay** [comment]
I think one thing that would help clarify some of the feature requests going on here is if people would make a mockup for how you want it to look and work for the user, then post a recording of it using [asciinema](https://asciinema.org).

**Comment by aleclarson** [comment]
Anyone here should check out #709 and give their thoughts on it. Cheers 🍻

**Comment by fstanisic** [comment]
I know this is almost 3 years old now, but maybe it will come in handy for someone:
I was able to make auto answering work with the use of fix from #665 

Example:

`const prompts = [
		{
			name: 'q',
			message: 'message',
			when: function (answers: Answers) {
				const testvar = process.env.TEST_VAR;
				if (testvar) {
					answers.q = testvar;
					return false;
				}
				return true;
			},
		},
	];

	const response = await inquirer.prompt(prompts);
	console.log(response);`

**Comment by benomatis** [comment]
In node I did...

```js
const args = process.argv.slice(2)
```

Then the prompt would look like this:
```js
{
    type: 'list',
    name: 'instance',
    message: 'Which instance do you want to run the script on?',
    choices: Object.keys(instanceMap),
    when(answers) {
        if (args.length > 0 && args[0] === 'local') {
            answers.instance = 'local'
            return false
        }
        return true
    }
}
```

And executed the script like this:
```
node script.js local
```

If I run it without the `local` argument, I get the prompt from inquirer, as expected.

**Comment by SBoudrias** [comment]
Ref https://github.com/SBoudrias/Inquirer.js/tree/main/packages/inquirer#inquirerpromptquestions-answers---promise

This was added a while back, the ability to provide an initial answer object that'll skip question with an answer pre-provided.
