### ISSUE TITLE
Rewrite into ES6

### ISSUE THREAD

**Issue by JPeer264** [SBoudrias/Inquirer.js#524]
As I saw it the lowest supported Node version is v4. So it would be good to rewrite the library step by step to ES6 (as far as it is supported by Node v4).

What you think about it?

**EDIT:**
I would also suggest to use babel for using more ES6 features.

**Comment by pietrovismara** [comment]
But why? 

Would there be any gain in rewriting the code? Could you elaborate on it? Or is it just because, you know, ES6?

Furthermore, i would strongly refrain from adding babel just for the sake of having new ways of doing the old stuff. Babel adds a big layer of complexity and in my experience it slows down development and debug quite a lot.

**Comment by antoine-pous** [comment]
In fact ES6 coding style is more clear, but i don't find babel usefull at all

**Comment by imkimchi** [comment]
Just think simple guys, writing Node in v4 is same as using iPhone 4 even though there's iPhone 8 coming out. Yeah, you could still use iPhone 4 but It's really slow, have a lower storage and can't even use LTE. 

Why would you use oldest version if there's more developed version?
Let's just use ES6 at least. You don't have to add babel.

**Comment by kbrandwijk** [comment]
Seems done.

**Comment by SBoudrias** [comment]
Indeed, thanks!
