### ISSUE TITLE
Auto-expand the expand

### ISSUE THREAD

**Issue by aaronshaf** [SBoudrias/Inquirer.js#60]
Is there a way to use the expand-type list, but in an auto-expanded way? Thanks!

**Comment by shayne** [comment]
It's easier to mistype the wrong index since the keys are all adjacent. Not necessarily a vote for supporting adding support in `rawlist` but perhaps adding an `expanded: true` optional property to expand. Also, is it necessary to re-collapse the expand list when you've made a selection. The cursor and character disappear on me, perhaps it's enough to type the letter and press enter w/o un-expanding the list.

**Comment by hi2u** [comment]
Is there still no way to have a menu of single letter keypresses that displays the menu by default and doesn't require the user to hit enter?

**Comment by GeorgeGkas** [comment]
@SBoudrias should we close this issue? If this is a design decision (and we cannot support this feature request), I do not see any other way to resolve this issue.

**Comment by heisian** [comment]
Upon further investigation, `iptraf` uses the [`ncurses`](https://en.wikipedia.org/wiki/Ncurses) library, created 25 years ago. I guess we're still reinventing the wheel.
