### ISSUE TITLE
Integration with vscode debugger

### ISSUE THREAD

**Issue by jmjpro** [SBoudrias/Inquirer.js#650]
Are there any special instructions to get this to work with a debugger (in particular, Visual Studio Code)? When launching via the debugger, I don't see any console output from `inquirer.prompt()`.

**Comment by SBoudrias** [comment]
Chances are that VS studio doesn't have full TTY support. I don't think you'd be able to get this working outside your terminal (or until VS add full TTY support)

**Comment by phobal** [comment]
And how do you debugger ? now. console.log ?

**Comment by SBoudrias** [comment]
I use the chrome devtool connected to the node remote debug process. This probably works similar with vs code

**Comment by SBoudrias** [comment]
If anyone want to send launch.json config for the project. I'll be happy to help merge it.

**Comment by sqren** [comment]
Example of launch.json with terminal that supports tty:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Start",
      "program": "<path to program>",
      "console": "integratedTerminal"
    }
  ]
}
```
This works really well for my use cases.

**Comment by 3CordGuy** [comment]
@sqren Thank you so much! 👍

**Comment by SBoudrias** [comment]
I'll close the ticket as there's @sqren [instructions](https://github.com/SBoudrias/Inquirer.js/issues/650#issuecomment-408620162) appears to work properly.

Thanks!

**Comment by stephencweiss** [comment]
I recognize this ticket was closed, but I'm a little confused about what the expected outcome from using the `integrated Terminal` should be. 

When I am debugging using the `integratedTerminal`, I _am_ able to see the prompts and interact, however, in my case, I seem to have no visibility into the state of the application. It's as if the program has already exited. 

<img width="1775" alt="Screen Shot 2020-10-11 at 4 54 03 PM" src="https://user-images.githubusercontent.com/39878535/95691123-603c2180-0be2-11eb-9135-49ddb7614f3f.png">

In the screen shot, you can see I have the prompt from my CLI available, the debugger has paused the process, but if you look  at the left nav - there's nothing in `variables`, the call stack _only_ has the debugger, etc. 

What am I missing? Since I'm using Inquirer in an async method, shouldn't I be able to step through and see the answers as they come _back_ from stdin?

FWIW - the question I'm currently debugging is [here](https://github.com/stephencweiss/note-mgr/blob/main/src/actions/interactiveNotePrompt.ts) (summarized below):

```
import { prompt } from "inquirer"
import dayjs from "dayjs"
import kebabCase from "lodash.kebabcase"
import {
    ConfigurationKeys,
    DocumentStages,
    FrontmatterKeys,
    IFrontmatter,
} from "../utils"

interface ISolicitNoteMetadata {
    title?: string
    config: Map<ConfigurationKeys, any>
    options: IFrontmatter
}

export async function solicitNoteMetadata({
    title,
    config,
    options,
}: ISolicitNoteMetadata) {
    const defaultDateFmt = config.get(ConfigurationKeys.DEFAULT_DATE_FORMAT)
    const questions = [
        {
            type: "input",
            name: "title",
            message: "What's the title for the note?",
            default: options["title"] || title,
        },
        //...
    ]

    await prompt(questions).then((answers) => {
        options["title"] = answers.title
        //...
    })
}

```

**Comment by oleksandr-yefremov** [comment]
In case someone will be looking for Intellij WebStorm debug config. You need to enable a registry flag first as described in [this ticket](https://youtrack.jetbrains.com/issue/WEB-13727#focus=Comments-27-2835917.0-0) to capture user input in terminal. Then create normal Node.js "Run Configuration" and point it to your index.js
