### ISSUE TITLE
Keeping question at the end of console

### ISSUE THREAD

**Issue by PaQ666** [SBoudrias/Inquirer.js#703]
Hi,

Is there any way to make inquirer question persistently at the end of console output? I have script with multiple asynchronous operations outputting to console, but I would like to have inquirer question persistent at the end of console no matter what - so users won't miss it even if a lot of additional text is logged.

Alternatively can I force rerendering from code? It is done internally whenever there is some user interaction with console - I would like to simply have such hook from script.

Thanks,
Rafal

**Comment by SBoudrias** [comment]
Hey @PaQ666,

This isn't something I've tried making work. You could get some inspiration from the `BottomBar` module in this repository - but it's not working out of the box with prompts.

**Comment by adamreisnz** [comment]
Would love to see this feature too, it's getting very messy when other console logs are displayed in the prompt.

**Comment by adamreisnz** [comment]
Any update on this issue?

**Comment by SBoudrias** [comment]
@adamreisnz it's not something I plan working on myself. I'm happy to help review the concept (before any PR) if someone wants to spend time working on such a feature.

**Comment by adamreisnz** [comment]
Would you be open to adding a new method to inquirer, e.g. something like `.log()` which could be used to log a simple line of text to the console, which would then push the question down again? This log could then be used instead of regular `console.log` commands, which tend to log data all over the inquirer interface.

**Comment by SBoudrias** [comment]
Could you provide an example how an end-user would use `inquirer.log()`? I'm not sure I fully understand in which context this is necessary.

**Comment by adamreisnz** [comment]
Yes, I'll provide a use case demo in a minute

**Comment by adamreisnz** [comment]
Right, that minute took longer than anticipated.

Here's how I use inquirer:

![image](https://user-images.githubusercontent.com/490562/58858655-26a8fb80-86fc-11e9-8382-f97ac779f885.png)

We have a little diagnostics script which allows us to connect to our hardware via serial port and send a variety of commands, as per above.

Whenever we send a command, we output the JSON string that gets sent and anything that is received on the serial port, for debugging purposes and diagnostics:

![image](https://user-images.githubusercontent.com/490562/58858741-56f09a00-86fc-11e9-8981-746bfe1bbd93.png)

Depending on the timing, these JSON logs can show up all throughout the inquirer interface:

![image](https://user-images.githubusercontent.com/490562/58858767-6c65c400-86fc-11e9-8763-d139a3367650.png)

In this latter example, the moment I navigate commands, the green received JSON response will be overwritten by inquirer, because it overwrites the line in the console.

So what I'm asking for, is a method on Inquirer to log a line to the console, and then have that line be logged above the last inquirer prompt, so that it persists in the console and won't be erased by subsequent prompts.

Much like happened in my first example:

**Comment by Nikhil-Vats** [comment]
Hey @SBoudrias, I have a somewhat similar issue. In my case, the previous prompt is shown again in terminal after console.log or this.log, hence the same question is printed twice - 

1. Once, when it is supposed to, when user has to answer it.
2. Second, after user enters the answer, I validate it asynchronously and log something to terminal, the question is printed again WITH the answer and the subsequent question.

I don't want this, I want a prompt to be shown only once. 

![Screenshot 2019-06-13 at 3 33 47 PM](https://user-images.githubusercontent.com/31413407/59424046-e549d780-8df0-11e9-8979-26778cc33e73.png)

**Comment by KeithBillings** [comment]
Here is another example of this issue: 

![Untitled_ Jul 28, 2020 2_02 PM (1)](https://user-images.githubusercontent.com/63262663/88849074-32783c80-d19e-11ea-8189-e982db345349.gif)

I have a inquirer prompt asking for a user selection, then returning a response from a database, then looping. The prompts are overwriting the response tables.
