### ISSUE TITLE
Add flag to accept all defaults.

### ISSUE THREAD

**Issue by shannonmoeller** [SBoudrias/Inquirer.js#74]
I'd like to give the users of my yeoman generator the ability to specify a flag to accept all default prompt answers. This feature was in the works before yeoman was updated to use (the quite superior) `inquirer`.

I propose the addition of an optional `options` argument to the `inquirer.prompt` method:

``` javascript
inquirer.prompt(prompts, [options,] callback)
```

Where options may contain the following (or similar) flags:
- `askDefaults` _boolean_ : `false` User is presented with a list of all prompts and their default answers and is given the choice to accept the defaults or change answers.
- `useDefaults` _boolean_ : `false` User is not prompted for any input. All default values are accepted and immediately passed to the callback.

Related Yeoman issue: https://github.com/yeoman/generator/issues/277

**Comment by johannesjo** [comment]
I would find this very useful!

**Comment by shannonmoeller** [comment]
Are you saying that something like this is possible now?

`yes | yo your-gen`

Based on those examples I’m not sure you quite understand what I’m asking for. :)

**Comment by GeorgeGkas** [comment]
@shannonmoeller my answer was regarding your original proposal of adding an optional options argument, which was addressed by using `default` key in question objects. As for the example of Yeoman the best you do is to test it and post the results. This issue is old and it's better to open a new one if there is still an issue. You'll have more chance to get an answer. Also, you can open a new issue in Yeoman repo.

**Comment by shannonmoeller** [comment]
It is old and I haven’t used inquirer recently. Just know that the default field isn’t what I was talking about. :)

**Comment by GeorgeGkas** [comment]
Okay thank you for the clarification. :+1:

**Comment by valerybugakov** [comment]
@GeorgeGkas is there a solution for this issue at the moment? Something similar to `npm -y` flag.
