### ISSUE TITLE
Command/option to go back a question

### ISSUE THREAD

**Issue by Eken92** [SBoudrias/Inquirer.js#876]
Hi,

I am wondering if inbuilt support for going back in questions is in scope? For example, always providing an (always) visible option to press "Back"? Or by tapping a keystroke (ctrl+b) or so.

I am aware that this is probably possible to code using nested prompts and so, having really figured out how yet though. 

But maybe this isn't something that inquirer would be suitable for, I just got started with this great module and is trying to use it to it fullest.

I don't know how I am supposed to add tags, but it shouldn't be an issue, it should be enhancement/feature.

Thanks!

**Comment by dnhook123** [comment]
Any updates on this?

**Comment by nopeless** [comment]
Same questioin

**Comment by SBoudrias** [comment]
Hi, this feature is not inline with the direction I want the project to involve in. That is, limiting/removing flow control from the library since it isn't necessary in modern Node. See release notes on #1214 

As for a back implementation, we do that with minimal code in our demo package: https://github.com/SBoudrias/Inquirer.js/blob/master/packages/demo/index.mjs
