### ISSUE TITLE
Prevent exiting of process after prompt conclusion

### ISSUE THREAD

**Issue by szul** [SBoudrias/Inquirer.js#894]
Maybe I'm missing this in the docs, but I have my own CLI that reads input/output, and I want to use inquirer just for certain prompts (e.g., choices). The problem is that when the inquirer workflow ends, the process exits, so my CLI stops and returns me to the command prompt. Is there something I need to do with the 'line' or 'close' events to prevent this?

**Comment by SBoudrias** [comment]
You should not have to. If your program still have listeners actives or JS code running, the process shouldn't exit automatically.

Are you sure this is not an issue in your own code?

**Comment by szul** [comment]
I already have a `readline` instance reading the line of user input (`read.on('line')`). Throughout my workflow, the back and forth between console and user is fine. If the user types in a specific keyword, I launch the prompt via:

```
prompt('activePrompt').then((answers) => console.log(`Got: ${answers['activePrompt']}`));
```

> The logging is just me testing...

This successful puts me into the prompt, but when the prompt is over the command line program exists entirely, not just the prompt. It doesn't pass control back.

Am I missing an event capture somewhere?

**Comment by SBoudrias** [comment]
This might be because we need to call:

```js
    this.rl.output.end();
    this.rl.pause();
    this.rl.close();
```

When ending the prompt. You can see this inside https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/lib/ui/baseUI.js

The problem is that Node doesn't really work well with multiple readline instances running at the same time (I'm not too familiar with the internal implementation anymore, but a while ago it was pretty much a singleton). The problem, if inquirer don't close its readline instance, then the prompt stays hanging forever and control will no go back to the user.

Maybe an option could be to by-pass closing the readline and leaving this responsibility to the user if they pass the readline instance as an argument; or the an stdin instance (or maybe simpler if we just add an option `keepAlive` that will not close the readline after running). This would also happen in `baseUI` if you'd like to take a stab at it.

**Comment by szul** [comment]
Ok. Go ahead and assign this to me, and I'll try to tackle it when I come back around to the utility. Thanks!

**Comment by AdamBD** [comment]
any news on this one?

**Comment by RonWang** [comment]
Bumping this thread. Is supporting readline injection the only way to let repl and inquirer work together?

**Comment by esmiralha** [comment]
up up! any news?

**Comment by szul** [comment]
Went a completely different route with this and ended up writing the choices out myself and using ansi escape sequences to move the cursor for selection. For my implementation, it made more sense to focus on the minimal code needed to do that. Closing this since I originally opened it for a specific use case. Feel free to re-open if this is something planned for the project.

**Comment by JoCat** [comment]
Today I faced a similar problem. What helped in my case was closing my readline interface, executing the inquirer code, and then reinitializing my readline interface.

**Comment by SBoudrias** [comment]
> What helped in my case was closing my readline interface, executing the inquirer code, and then reinitializing my readline interface.

Yes, this is unfortunately always required. I'm not sure why, but Node.js readline only work when there's a single instance. Another work around might be to use different stdin/stdout set on each readline instance; but maybe not (and might not work in all cases anyway since for Inquirer you likely need the terminal stdin/stdout).

**Comment by Darkosphere** [comment]
> Today I faced a similar problem. What helped in my case was closing my readline interface, executing the inquirer code, and then reinitializing my readline interface.

Would you mind to share a short example on how to perform that as I'm currently struggling to sort out this issue.

I just figured it out it's coming from a conflict with inquirer as I was trying to implement a **press a key to continue** functionnality and my tests are working fine when not used in combination with inquirer but when they are they just stop working.

**Comment by JoCat** [comment]
everything is so, you can still move the interface creation code into a function so as not to repeat

**Comment by JacksonTian** [comment]
Add rl.pause() can resolve it.
